[package]
name = "advent-of-code-2018"
version = "0.1.0"
authors = ["Tyler Hallada <tyler@hallada.net>"]
edition = "2018"

[dependencies]
chrono = "0.4"
lazy_static = "1.2.0"
regex = "1"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "day_11"
harness = false
